###
GET http://localhost:8080/games
Content-Type: application/json

###
POST http://localhost:8080/games
Content-Type: application/json
Authorization: Basic user password

{
  "name": "Quake III",
  "category": "Shooter",
  "rating": 10,
  "price": 666,
  "releaseDate": "31-12-2021 13:42:00",
  "publisherId": 1
}

###
POST http://localhost:8080/publishers
Content-Type: application/json
Authorization: Basic user password

{
  "name": "Electronic Arts"
}
